version: '3.7'

services:
  app:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_HOST: db
      DB_VENDOR: mysql
      DB_DATABASE: keycloak
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - 8080:8080
    volumes:
      - ./themes/custom:/opt/jboss/keycloak/themes/custom
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: keycloak-mysql
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 33306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql