version: '3.7'

services:
  neo4j:
    image: neo4j:5.5
    restart: unless-stopped
    ports:
      - 7474:7474 # HTTP
      - 7473:7473 # HTTPS
      - 7687:7687 # Bolt
    volumes:
      - ./__seed__:/var/lib/neo4j/__seed__
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G

      - DB_HOST=localhost
      - DB_PORT=7474
      - DB_USER=neo4j
      - DB_PASSWORD=neo4j

      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_allow__upgrade=true

      - NEO4J_dbms_db_timezone=SYSTEM
      - NEO4J_db_temporal_timezone=America/Sao_Paulo
      - NEO4JLABS_PLUGINS='["apoc"]'