apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: dummy
          image: keda-sample/dummy-app
          imagePullPolicy: Never
          lifecycle:
            preStop:
              exec:
                command:
                  - pkill -f "sleep"
          env:
            - name: REDIS_ADDRESS
              value: "redis.default:6379"