apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: deploy-b
    spec:
      containers:
      - name: nginx-version-b
        image: nginx:1.14.2
        ports:
        - containerPort: 80