apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-node-server
  namespace: spv
spec:
  selector:
    matchLabels:
      app: gitops-node-server
  template:
    metadata:
      labels:
        app: gitops-node-server
    spec:
      containers:
      - name: gitops-node-server
        image: gitops-node-server
        ports:
        - containerPort: 8080