version: '3.7'

services:
  mongo:
    image: mongo
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGO_INITDB_DATABASE=newsfeed
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017