apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a
spec:
  replicas: 8
  selector:
    matchLabels:
      app: sample-nginx-app
  template:
    metadata:
      labels:
        app: sample-nginx-app
        version: deploy-a
    spec:
      containers:
      - name: nginx-version-a
        image: nginx:1.14.2
        ports:
        - containerPort: 80